version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python -m flask run --host=0.0.0.0

  test:
    build: .
    command: python -m pytest
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    depends_on:
      - web